Repository redferret/black_thursday, pull requests merged in 2021-04, with the labels that each got.

#5 Add DTR file
  DTR.md
Labels: documentation

#7 Add SimpleCov to Gem file
  Gemfile
  Gemfile.lock
Labels: enhancement

#9 Setup hound ci
  .hound.yml
  .rubocop.yml
  Gemfile
Labels: enhancement

#41 Rename test to spec
  lib/merchant_repository.rb
  spec/.gitignore
  spec/merchant_repository_spec.rb
Labels: enhancement

#55 Enable/Disable/Modify Cops
  .rubocop.yml
Labels: documentation

#75 Refactor MockData Class
  .rubocop.yml
  data/mock_data.rb
  spec/item_repository_spec.rb
  spec/merchant_repository_spec.rb
  spec/mock_data_spec.rb
  spec/sales_engine_spec.rb
Labels: Refactoring

#83 Create invoice repository
  lib/invoice.rb
  lib/invoice_repository.rb
  lib/item.rb
  spec/invoice_item_spec.rb
  spec/invoice_repository_spec.rb
  spec/invoice_spec.rb
Labels: Iteration 2, enhancement

#85 Break MockData class into separate mock files
  .rubocop.yml
  data/invoice_item_mocks.rb
  data/invoice_mocks.rb
  data/item_mocks.rb
  data/merchant_mocks.rb
  data/mock_data.rb
  data/mockable.rb
  spec/invoice_item_mocks_spec.rb
  spec/invoice_mocks_spec.rb
  spec/invoice_repository_spec.rb
  spec/item_mocks_spec.rb
  spec/item_repository_spec.rb
  spec/item_spec.rb
  spec/merchant_mocks_spec.rb
  spec/merchant_repository_spec.rb
  spec/mock_data_spec.rb
  spec/mockable_spec.rb
  spec/sales_engine_spec.rb
Labels: Refactoring

#90 Update SalesAnalyst with test for #golden_items
  spec/sales_analyst_mocks.rb
  spec/sales_analyst_spec.rb
Labels: Iteration 1, Refactoring

#88 Refactor SalesEngine for add'l repositories
  lib/customer.rb
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  lib/invoice_repository.rb
  lib/sales_analyst.rb
  lib/sales_engine.rb
  lib/transaction_repository.rb
  spec/invoice_item_repository_spec.rb
  spec/sales_analyst_mocks.rb
  spec/sales_analyst_spec.rb
  spec/sales_engine_spec.rb
Labels: Iteration 0, Iteration 1, Iteration 2, Iteration 3, Refactoring

#89 Refactor Invoice and InvoiceRepo classes to pass Spec Harness
  lib/invoice.rb
  spec/file_io_spec.rb
  spec/invoice_spec.rb
  spec/sales_analyst_mocks.rb
Labels: Iteration 2, Refactoring

#95 Refactor Transaction and TransactionRepo classes to pass Spec Harness
  lib/transaction.rb
  lib/transaction_repository.rb
Labels: Iteration 3, Refactoring

#100 Create Customer and Transaction mocks with necessary refactoring
  data/customer_mocks.rb
  data/invoice_item_mocks.rb
  data/invoice_mocks.rb
  data/item_mocks.rb
  data/merchant_mocks.rb
  data/mockable.rb
  data/transaction_mocks.rb
  lib/sales_engine.rb
  spec/customer_mocks_spec.rb
  spec/customer_repository_spec.rb
  spec/invoice_item_mocks_spec.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_mocks_spec.rb
  spec/invoice_repository_spec.rb
  spec/item_mocks_spec.rb
  spec/item_repository_spec.rb
  spec/mockable_spec.rb
  spec/sales_analyst_mocks.rb
  spec/sales_engine_mocks.rb
  spec/sales_engine_mocks_spec.rb
  spec/sales_engine_spec.rb
  spec/transaction_mocks_spec.rb
  spec/transaction_repository_spec.rb
Labels: Refactoring, enhancement

#102 Add tests for Item helper methods
  spec/item_repository_spec.rb
  spec/item_spec.rb
Labels: Iteration 0, Refactoring

#103 Change created and updated at to Time.parse
  spec/invoice_item_spec.rb
Labels: Iteration 3, bug

#104 Feature BI for Invoices
  lib/sales_analyst.rb
  lib/sales_engine.rb
  spec/sales_analyst_mocks.rb
  spec/sales_analyst_spec.rb
Labels: enhancement

#110 Update SalesAnalyst with Iteration 4 methods
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  lib/merchant_repository.rb
  lib/sales_analyst.rb
  lib/sales_engine.rb
  lib/transaction.rb
  lib/transaction_repository.rb
  spec/invoice_item_mocks_spec.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_item_spec.rb
  spec/sales_analyst_mocks.rb
  spec/sales_analyst_mocks_spec.rb
  spec/sales_analyst_spec.rb
  spec/transaction_repository_spec.rb
  spec/transaction_spec.rb
Labels: Iteration 4, enhancement

#107 Refactor for inheritance
  lib/customer.rb
  lib/customer_repository.rb
  lib/file_io.rb
  lib/invoice.rb
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  lib/invoice_repository.rb
  lib/item.rb
  lib/item_repository.rb
  lib/merchant.rb
  lib/merchant_repository.rb
  lib/model.rb
  lib/repository.rb
  lib/transaction.rb
  lib/transaction_repository.rb
  spec/customer_repository_spec.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_repository_spec.rb
  spec/item_repository_spec.rb
  spec/merchant_repository_spec.rb
  spec/sales_analyst_mocks.rb
  spec/sales_engine_mocks.rb
  spec/sales_engine_spec.rb
  spec/transaction_repository_spec.rb
Labels: Refactoring

#112 Fix spec harness
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  lib/customer.rb
  lib/invoice.rb
  lib/invoice_item.rb
  lib/item.rb
  lib/merchant.rb
  lib/merchant_repository.rb
  lib/repository.rb
  lib/transaction.rb
Labels: bug

#115 Refactor/mock data files fix conflict
  coverage/.resultset.json
  coverage/index.html
  data/sales_analyst_mocks.rb
  data/sales_engine_mocks.rb
  lib/sales_analyst.rb
  spec/invoice_mocks_spec.rb
  spec/invoice_repository_spec.rb
  spec/invoice_spec.rb
  spec/item_mocks_spec.rb
  spec/item_repository_spec.rb
  spec/merchant_mocks_spec.rb
  spec/merchant_repository_spec.rb
  spec/merchant_spec.rb
  spec/mockable_spec.rb
  spec/sales_analyst_mocks_spec.rb
  spec/sales_analyst_spec.rb
  spec/sales_engine_mocks_spec.rb
  spec/sales_engine_spec.rb
  spec/transaction_mocks_spec.rb
Labels: Refactoring
